### 1️⃣ Guest Login (Create Guest Session)
POST http://localhost:3000/guest-user
# Content-Type: application/json

### 2️⃣ Protected Route: Access Guest Profile (Pass guestId in headers)

POST http://localhost:3000/guest-user/validate/aad3259f-f6f7-42e2-8962-1f226673130a

PATCH http://localhost:3000/guest-user/519eb47a-7026-4dcf-a698-9e754b5e13d6
Content-Type: application/json

{
  "won": true
}
GET http://localhost:3000/guest-user/profile
guest-id: {d30a3385-4b22-46a2-8e0f-8440e94afe81}

### 3️⃣ Logout Guest (Deletes session)
DELETE http://localhost:3000/guest-user/logout
guest-id: {d30a3385-4b22-46a2-8e0f-8440e94afe81}

### 4️⃣ Test Expired Guest Session (Wait 10 mins before running)
GET http://localhost:3000/guest-user/profile
guest-id: {f144972e-37ac-4719-bcc3-19156138d43e}

GET http://localhost:3000/guest-user/519eb47a-7026-4dcf-a698-9e754b5e13d6/result


